/**
 * Fonte única do acervo de certificados.
 *
 * Os 148 certificados com arquivo foram extraídos da varredura das pastas
 * public/arquivos/cursos e public/arquivos/eventos: o nome do arquivo dá emissor,
 * título e data; o texto do documento dá carga horária, papel e código de validação.
 * Doze deles não tinham camada de texto e foram lidos visualmente.
 *
 * Os 13 registros de comprovação guardam apenas a camada de prova. Organização,
 * cargo e período vêm do resume.data.ts pela âncora, para não haver duas verdades.
 *
 * A seção de cada item é um campo do dado, não regra de componente: mudar o
 * agrupamento da grade é editar este arquivo.
 */

import type { Certificate } from "./types";

export const certificates: Certificate[] = [
  /* ---------------- Registros de comprovação ---------------- */
  {
    id: "reg-estacio-ads",
    secao: "Formação e trajetória",
    data: "2026-07",
    evidencia: "registro",
    natureza: "oficial",
    ancora: "estacio",
    organizacao: "Centro Universitário Estácio de Santa Catarina",
    documento: "Diploma de curso superior de tecnologia",
    comprova: "Conclusão do curso e o título de tecnólogo em Análise e Desenvolvimento de Sistemas.",
    nota: "Conclusão em 05/07/2026 e colação de grau em 24/07/2026. O diploma traz código de validação verificável no portal da instituição.",
  },
  {
    id: "reg-ifsudestemg",
    secao: "Formação e trajetória",
    data: "2020-03",
    evidencia: "registro",
    natureza: "oficial",
    ancora: "ifsudestemg",
    organizacao: "IF Sudeste MG — Campus Juiz de Fora",
    documento: "Diploma, histórico e documentos de estágio",
    comprova: "Conclusão do curso Técnico em Informática e as disciplinas cursadas.",
    nota: "O período indicado é o de realização do curso. O diploma registra a conclusão em 02/03/2020 e foi expedido em 02/06/2023.",
  },
  {
    id: "reg-ufjf",
    secao: "Formação e trajetória",
    data: "2016-03",
    evidencia: "registro",
    natureza: "oficial",
    ancora: "ufjf",
    organizacao: "UFJF — Departamento de Ciência da Computação",
    documento: "Histórico escolar emitido pela CDARA",
    comprova: "Disciplinas cursadas e a carga horária integralizada no curso de Ciência da Computação.",
    nota: "Ingresso em 2008 por Programa de Ingresso Seletivo Misto, curso noturno, 1.260 horas integralizadas.",
  },
  {
    id: "reg-codejr",
    secao: "Formação e trajetória",
    data: "2015-12",
    evidencia: "registro",
    natureza: "nao-oficial",
    ancora: "codejr",
    organizacao: "CodeJr — Empresa júnior de Computação da UFJF",
    documento: "Dez comunicações internas de 2015 e um relatório de trabalho",
    comprova: "A atuação nas gestões, pelo uso do e-mail institucional e pelos documentos em que atuou.",
    nota: "Não existe declaração institucional emitida pela CodeJr. O registro é sustentado por comunicações de época, datadas de agosto a dezembro de 2015, envolvendo Estatuto Social, Regimento Interno, planejamento estratégico e o Processo Único de Federação da FEJEMG.",
  },
  {
    id: "reg-brasil-center",
    secao: "Formação e trajetória",
    data: "2019-09",
    evidencia: "registro",
    natureza: "oficial",
    ancora: "brasil-center-sup",
    organizacao: "Brasil Center Comunicações",
    documento: "Dois registros em carteira de trabalho",
    comprova: "Dois vínculos distintos com o mesmo empregador, de 2009 e de 2015 a 2019.",
    nota: "O primeiro é contrato de aprendiz, encerrado em dezembro de 2009. O segundo vai de setembro de 2015 a setembro de 2019.",
  },
  {
    id: "reg-almaviva",
    secao: "Formação e trajetória",
    data: "2019-10",
    evidencia: "registro",
    natureza: "oficial",
    ancora: "almaviva",
    organizacao: "AlmavivA do Brasil",
    documento: "Registro em carteira de trabalho",
    comprova: "O vínculo e o cargo de supervisão em teleatendimento.",
  },
  {
    id: "reg-nvoip",
    secao: "Formação e trajetória",
    data: "2021-08",
    evidencia: "registro",
    natureza: "oficial",
    ancora: "nvoip-dev",
    organizacao: "Nvoip",
    documento: "Registro em carteira de trabalho",
    comprova: "O vínculo e a atuação em desenvolvimento, registrada sob o CBO 2124-05.",
  },
  {
    id: "reg-abc",
    secao: "Formação e trajetória",
    data: "2025-02",
    evidencia: "registro",
    natureza: "oficial",
    ancora: "abc-construcao",
    organizacao: "ABC da Construção",
    documento: "Ficha de registro de empregados e termo de compromisso de estágio",
    comprova: "O início do vínculo, em julho de 2023, e a área de atuação.",
    nota: "A ABC da Construção e o Grupo MYSA compartilham o mesmo CNPJ: é a mesma empresa, com alteração de razão social.",
  },
  {
    id: "reg-mysa",
    secao: "Formação e trajetória",
    data: "2026-02",
    evidencia: "registro",
    natureza: "oficial",
    ancora: "mysa",
    organizacao: "Grupo MYSA",
    documento: "Registro em carteira de trabalho e contrato de prestação de serviços",
    comprova: "O vínculo com a holding formada a partir da ABC da Construção.",
    nota: "O trabalho foi contínuo desde a ABC da Construção, com mudança de razão social e de fonte pagadora.",
  },
  {
    id: "reg-volta-express",
    secao: "Formação e trajetória",
    data: "2026-09",
    evidencia: "registro",
    natureza: "nao-oficial",
    ancora: "volta-express",
    organizacao: "Volta Express Brasil",
    documento: "Certificado do CRITT — UFJF",
    comprova: "A apresentação do projeto na fase classificatória do processo de incubação.",
    nota: "A empresa está em processo de incubação e regularização. Apresentação feita no MA2, evento de análise de pitch do CRITT/UFJF, em setembro de 2026.",
  },
  {
    id: "reg-oficina-da-net",
    secao: "Produção pública",
    data: "2014-08",
    evidencia: "registro",
    natureza: "oficial",
    ancora: "oficina-da-net",
    organizacao: "Oficina da Net",
    documento: "Seis artigos assinados e datados pelo veículo",
    comprova: "A autoria e a publicação dos artigos, entre janeiro e agosto de 2014.",
    nota: "Oficina da Net é publicação digital especializada em tecnologia. Não possui registro ISSN.",
  },
  {
    id: "reg-github",
    secao: "Produção pública",
    data: "2026-09",
    evidencia: "ao-vivo",
    natureza: "ao-vivo",
    ancora: "volta-express",
    organizacao: "GitHub",
    documento: "Perfil público, lido da API",
    comprova: "Repositórios, projetos com link em produção e atividade de código.",
    destino: "/projetos",
  },
  {
    id: "reg-medium",
    secao: "Produção pública",
    data: "2026-09",
    evidencia: "ao-vivo",
    natureza: "ao-vivo",
    ancora: "oficina-da-net",
    organizacao: "Medium",
    documento: "Perfil público, lido do feed",
    comprova: "Artigos publicados, alcance e proporção de leitura.",
    destino: "/blog",
  },

  /* ---------------- Certificados com arquivo ---------------- */
  { id: "abc-grc1-00-lgpd-os-dez-principios-da-lei-com-quiz", secao: "ABC — Programa GRC1", data: "2024-06-19", evidencia: "arquivo", emissor: "ABC da Construção", titulo: "LGPD: Os dez princípios da lei (com quiz)", arquivo: "cursos/abc-grc1-00-lgpd-os-dez-principios-da-lei-com-quiz.pdf", programa: "Programa GRC1", duracao: "10 min", horas: 0.167 },
  { id: "abc-grc1-01-the-inside-man-t2-ep04-o-santo-graal", secao: "ABC — Programa GRC1", data: "2024-06-19", evidencia: "arquivo", emissor: "ABC da Construção", titulo: "The Inside Man: Temporada 2, Ep 04 - O Santo Graal (Internet das", arquivo: "cursos/abc-grc1-01-the-inside-man-t2-ep04-o-santo-graal.pdf", programa: "Programa GRC1", duracao: "7 min", horas: 0.117 },
  { id: "abc-grc1-02-the-inside-man-t2-ep03-temos-um-encontro-marcado", secao: "ABC — Programa GRC1", data: "2024-05-31", evidencia: "arquivo", emissor: "ABC da Construção", titulo: "The Inside Man: Temporada 2, Ep 03 - Temos um encontro marcado (Dispositivos", arquivo: "cursos/abc-grc1-02-the-inside-man-t2-ep03-temos-um-encontro-marcado.pdf", programa: "Programa GRC1", duracao: "8 min", horas: 0.133 },
  { id: "abc-grc1-03-proteja-se-do-ransomware-com-quiz", secao: "ABC — Programa GRC1", data: "2024-04-26", evidencia: "arquivo", emissor: "ABC da Construção", titulo: "Proteja-se do Ransomware com Quiz", arquivo: "cursos/abc-grc1-03-proteja-se-do-ransomware-com-quiz.pdf", programa: "Programa GRC1", duracao: "13 min", horas: 0.217 },
  { id: "abc-grc1-04-the-inside-man-t2-ep02-equipe-em-ruptura", secao: "ABC — Programa GRC1", data: "2024-04-02", evidencia: "arquivo", emissor: "ABC da Construção", titulo: "The Inside Man: Temporada 2, Ep 02 - Equipe em ruptura (O que você precisa", arquivo: "cursos/abc-grc1-04-the-inside-man-t2-ep02-equipe-em-ruptura.pdf", programa: "Programa GRC1", duracao: "8 min", horas: 0.133 },
  { id: "abc-grc1-05-the-inside-man-t2-ep00-trailer", secao: "ABC — Programa GRC1", data: "2024-03-12", evidencia: "arquivo", emissor: "ABC da Construção", titulo: "The Inside Man: Temporada 2, Ep 00 - Trailer", arquivo: "cursos/abc-grc1-05-the-inside-man-t2-ep00-trailer.pdf", programa: "Programa GRC1", duracao: "2 min", horas: 0.033 },
  { id: "abc-grc1-06-the-inside-man-t2-ep01-uma-melodia-diferente", secao: "ABC — Programa GRC1", data: "2024-03-12", evidencia: "arquivo", emissor: "ABC da Construção", titulo: "The Inside Man: Temporada 2, Ep 01 - Uma melodia diferente (Dispositivos móveis)", arquivo: "cursos/abc-grc1-06-the-inside-man-t2-ep01-uma-melodia-diferente.pdf", programa: "Programa GRC1", duracao: "8 min", horas: 0.133 },
  { id: "abc-grc1-07-ameaca-interna-t1-ep01-o-novato", secao: "ABC — Programa GRC1", data: "2024-03-15", evidencia: "arquivo", emissor: "ABC da Construção", titulo: "Ameaça Interna: Temporada 1 Ep. 1 - O novato (Engenharia social)", arquivo: "cursos/abc-grc1-07-ameaca-interna-t1-ep01-o-novato.pdf", programa: "Programa GRC1", duracao: "8 min", horas: 0.133 },
  { id: "abc-grc1-08-ameaca-interna-t1-ep02-socializando", secao: "ABC — Programa GRC1", data: "2024-03-15", evidencia: "arquivo", emissor: "ABC da Construção", titulo: "Ameaça Interna: Temporada 1 Ep. 2 - Socializando (Redes sociais)", arquivo: "cursos/abc-grc1-08-ameaca-interna-t1-ep02-socializando.pdf", programa: "Programa GRC1", duracao: "7 min", horas: 0.117 },
  { id: "abc-grc1-09-ameaca-interna-t1-ep03-no-nosso-time", secao: "ABC — Programa GRC1", data: "2024-03-15", evidencia: "arquivo", emissor: "ABC da Construção", titulo: "Ameaça Interna: Temporada 1 Ep. 3 - No nosso time (Ataques de phishing)", arquivo: "cursos/abc-grc1-09-ameaca-interna-t1-ep03-no-nosso-time.pdf", programa: "Programa GRC1", duracao: "7 min", horas: 0.117 },
  { id: "abc-grc1-10-ameaca-interna-t1-ep04-surpresa", secao: "ABC — Programa GRC1", data: "2024-03-15", evidencia: "arquivo", emissor: "ABC da Construção", titulo: "Ameaça Interna: Temporada 1 Ep. 4 - Surpresa (Eliminação de documentos)", arquivo: "cursos/abc-grc1-10-ameaca-interna-t1-ep04-surpresa.pdf", programa: "Programa GRC1", duracao: "6 min", horas: 0.1 },
  { id: "abc-grc1-11-ameaca-interna-t1-ep05-na-encruzilhada", secao: "ABC — Programa GRC1", data: "2024-03-15", evidencia: "arquivo", emissor: "ABC da Construção", titulo: "Ameaça Interna: Temporada 1 Ep. 5 - Na encruzilhada (Política de mesa limpa)", arquivo: "cursos/abc-grc1-11-ameaca-interna-t1-ep05-na-encruzilhada.pdf", programa: "Programa GRC1", duracao: "6 min", horas: 0.1 },
  { id: "abc-grc1-12-ameaca-interna-t1-ep06-fantasia", secao: "ABC — Programa GRC1", data: "2024-03-15", evidencia: "arquivo", emissor: "ABC da Construção", titulo: "Ameaça Interna: Temporada 1 Ep. 6 - Fantasia (Serviços de nuvem)", arquivo: "cursos/abc-grc1-12-ameaca-interna-t1-ep06-fantasia.pdf", programa: "Programa GRC1", duracao: "10 min", horas: 0.167 },
  { id: "abc-grc1-13-ameaca-interna-t1-ep07-ganhando-tempo", secao: "ABC — Programa GRC1", data: "2024-03-15", evidencia: "arquivo", emissor: "ABC da Construção", titulo: "Ameaça Interna: Temporada 1 Ep. 7 - Ganhando tempo (Senhas)", arquivo: "cursos/abc-grc1-13-ameaca-interna-t1-ep07-ganhando-tempo.pdf", programa: "Programa GRC1", duracao: "6 min", horas: 0.1 },
  { id: "abc-grc1-14-ameaca-interna-t1-ep08-fisgada", secao: "ABC — Programa GRC1", data: "2024-04-02", evidencia: "arquivo", emissor: "ABC da Construção", titulo: "Ameaça Interna: Temporada 1 Ep. 8 - Fisgada (Ransomware)", arquivo: "cursos/abc-grc1-14-ameaca-interna-t1-ep08-fisgada.pdf", programa: "Programa GRC1", duracao: "6 min", horas: 0.1 },
  { id: "abc-grc1-15-ameaca-interna-t1-ep09-o-inimigo-esta-mais-perto", secao: "ABC — Programa GRC1", data: "2024-04-02", evidencia: "arquivo", emissor: "ABC da Construção", titulo: "Ameaça Interna: Temporada 1 Ep. 9 - O inimigo está mais perto (Segurança em", arquivo: "cursos/abc-grc1-15-ameaca-interna-t1-ep09-o-inimigo-esta-mais-perto.pdf", programa: "Programa GRC1", duracao: "7 min", horas: 0.117 },
  { id: "abc-grc1-16-ameaca-interna-t1-ep10-cuide-bem-de-suas-amizades", secao: "ABC — Programa GRC1", data: "2024-04-02", evidencia: "arquivo", emissor: "ABC da Construção", titulo: "Ameaça Interna: Temporada 1 Ep. 10 - Cuide bem de suas amizades (Segurança e", arquivo: "cursos/abc-grc1-16-ameaca-interna-t1-ep10-cuide-bem-de-suas-amizades.pdf", programa: "Programa GRC1", duracao: "9 min", horas: 0.15 },
  { id: "abc-grc1-17-ameaca-interna-t1-ep11-informacao-e-poder", secao: "ABC — Programa GRC1", data: "2024-04-02", evidencia: "arquivo", emissor: "ABC da Construção", titulo: "Ameaça Interna: Temporada 1 Ep. 11 - Informação é poder (Dispositivos externos)", arquivo: "cursos/abc-grc1-17-ameaca-interna-t1-ep11-informacao-e-poder.pdf", programa: "Programa GRC1", duracao: "6 min", horas: 0.1 },
  { id: "abc-grc1-18-ameaca-interna-t1-ep12-xeque-mate", secao: "ABC — Programa GRC1", data: "2024-04-02", evidencia: "arquivo", emissor: "ABC da Construção", titulo: "Ameaça Interna: Temporada 1 Ep. 12 - Xeque-mate (Ameaças internas)", arquivo: "cursos/abc-grc1-18-ameaca-interna-t1-ep12-xeque-mate.pdf", programa: "Programa GRC1", duracao: "7 min", horas: 0.117 },
  { id: "abc-grc1-19-the-inside-man-t2-ep07-mesa-para-dois", secao: "ABC — Programa GRC1", data: "2024-09-02", evidencia: "arquivo", emissor: "ABC da Construção", titulo: "The Inside Man: Temporada 2, Ep 07 - Mesa para dois (Senhas/Aplicativos de", arquivo: "cursos/abc-grc1-19-the-inside-man-t2-ep07-mesa-para-dois.pdf", programa: "Programa GRC1", duracao: "9 min", horas: 0.15 },
  { id: "abc-grc1-20-lgpd-direitos-do-titular-dos-dados-com-quiz", secao: "ABC — Programa GRC1", data: "2024-09-19", evidencia: "arquivo", emissor: "ABC da Construção", titulo: "LGPD: Direitos do titular dos dados (com quiz)", arquivo: "cursos/abc-grc1-20-lgpd-direitos-do-titular-dos-dados-com-quiz.pdf", programa: "Programa GRC1", duracao: "10 min", horas: 0.167 },
  { id: "abc-grc1-21-the-inside-man-t2-ep09-atras-da-cortina", secao: "ABC — Programa GRC1", data: "2024-11-04", evidencia: "arquivo", emissor: "ABC da Construção", titulo: "The Inside Man: Temporada 2, Ep 09 - Atrás da cortina (Engenharia social)", arquivo: "cursos/abc-grc1-21-the-inside-man-t2-ep09-atras-da-cortina.pdf", programa: "Programa GRC1", duracao: "7 min", horas: 0.117 },
  { id: "abc-grc1-22-the-inside-man-t2-ep10-confronto-final-no-curral-de-ia-parte-1", secao: "ABC — Programa GRC1", data: "2024-12-02", evidencia: "arquivo", emissor: "ABC da Construção", titulo: "The Inside Man: Temporada 2, Ep 10 - Confronto final no curral de IA - Parte 1", arquivo: "cursos/abc-grc1-22-the-inside-man-t2-ep10-confronto-final-no-curral-de-ia-parte-1.pdf", programa: "Programa GRC1", duracao: "8 min", horas: 0.133 },
  { id: "abc-grc1-23-como-criar-senhas-fortes", secao: "ABC — Programa GRC1", data: "2024-12-09", evidencia: "arquivo", emissor: "ABC da Construção", titulo: "Como criar senhas fortes", arquivo: "cursos/abc-grc1-23-como-criar-senhas-fortes.pdf", programa: "Programa GRC1", duracao: "6 min", horas: 0.1 },
  { id: "abc-grc1-24-the-inside-man-t2-ep11-confronto-final-no-curral-de-ia-parte-2", secao: "ABC — Programa GRC1", data: "2025-01-06", evidencia: "arquivo", emissor: "ABC da Construção", titulo: "The Inside Man: Temporada 2, Ep 11 - Confronto final no curral de IA. Parte 2", arquivo: "cursos/abc-grc1-24-the-inside-man-t2-ep11-confronto-final-no-curral-de-ia-parte-2.pdf", programa: "Programa GRC1", duracao: "9 min", horas: 0.15 },
  { id: "abc-grc1-25-the-inside-man-t2-ep12-um-novo-dia", secao: "ABC — Programa GRC1", data: "2025-02-05", evidencia: "arquivo", emissor: "ABC da Construção", titulo: "The Inside Man: Temporada 2, Ep 12 - Um novo dia (Internet das", arquivo: "cursos/abc-grc1-25-the-inside-man-t2-ep12-um-novo-dia.pdf", programa: "Programa GRC1", duracao: "11 min", horas: 0.183 },
  { id: "abc-grc1-26-lgpd-lei-geral-de-protecao-de-dados", secao: "ABC — Programa GRC1", data: "2025-02-10", evidencia: "arquivo", emissor: "ABC da Construção", titulo: "LGPD: Lei Geral de Proteção de Dados", arquivo: "cursos/abc-grc1-26-lgpd-lei-geral-de-protecao-de-dados.pdf", programa: "Programa GRC1", duracao: "13 min", horas: 0.217 },
  { id: "abc-grc1-27-the-inside-man-t3-ep01-teste-de-intrusao", secao: "ABC — Programa GRC1", data: "2025-03-10", evidencia: "arquivo", emissor: "ABC da Construção", titulo: "The Inside Man: Temporada 3 Ep 01 – Teste de Intrusão", arquivo: "cursos/abc-grc1-27-the-inside-man-t3-ep01-teste-de-intrusao.pdf", programa: "Programa GRC1", duracao: "8 min", horas: 0.133 },
  { id: "abc-grc1-28-seguranca-de-dispositivos-moveis", secao: "ABC — Programa GRC1", data: "2025-03-17", evidencia: "arquivo", emissor: "ABC da Construção", titulo: "Segurança de dispositivos móveis", arquivo: "cursos/abc-grc1-28-seguranca-de-dispositivos-moveis.pdf", programa: "Programa GRC1", duracao: "12 min", horas: 0.2, papel: "Concluinte" },
  { id: "abc-grc1-29-the-inside-man-t3-ep02-desafio-aceito", secao: "ABC — Programa GRC1", data: "2025-04-03", evidencia: "arquivo", emissor: "ABC da Construção", titulo: "The Inside Man: Temporada 3 Ep 02 – Desafio Aceito", arquivo: "cursos/abc-grc1-29-the-inside-man-t3-ep02-desafio-aceito.pdf", programa: "Programa GRC1", duracao: "6 min", horas: 0.1, papel: "Concluinte" },
  { id: "abc-grc1-30-pii-a-seguranca-e-voce", secao: "ABC — Programa GRC1", data: "2025-07-31", evidencia: "arquivo", emissor: "ABC da Construção", titulo: "PII, a segurança e você", arquivo: "cursos/abc-grc1-30-pii-a-seguranca-e-voce.pdf", programa: "Programa GRC1", duracao: "8 min", horas: 0.133 },
  { id: "abc-grc1-31-the-inside-man-t3-ep03-coisas-nao-ditas", secao: "ABC — Programa GRC1", data: "2025-07-16", evidencia: "arquivo", emissor: "ABC da Construção", titulo: "The Inside Man: Temporada 3 Ep 03 – Coisas Não Ditas", arquivo: "cursos/abc-grc1-31-the-inside-man-t3-ep03-coisas-nao-ditas.pdf", programa: "Programa GRC1", duracao: "8 min", horas: 0.133 },
  { id: "abc-grc1-32-the-inside-man-t3-ep04-credito-a-quem-e-devido", secao: "ABC — Programa GRC1", data: "2025-08-14", evidencia: "arquivo", emissor: "ABC da Construção", titulo: "The Inside Man: Temporada 3 Ep 04 – Crédito a Quem é Devido", arquivo: "cursos/abc-grc1-32-the-inside-man-t3-ep04-credito-a-quem-e-devido.pdf", programa: "Programa GRC1", duracao: "8 min", horas: 0.133 },
  { id: "abc-grc1-33-os-fundamentos-da-inteligencia-artificial", secao: "ABC — Programa GRC1", data: "2025-08-14", evidencia: "arquivo", emissor: "ABC da Construção", titulo: "Os fundamentos da inteligência artificial", arquivo: "cursos/abc-grc1-33-os-fundamentos-da-inteligencia-artificial.pdf", programa: "Programa GRC1", duracao: "10 min", horas: 0.167 },
  { id: "abc-grc1-34-the-inside-man-t3-ep05-a-verdade-vos-libertara", secao: "ABC — Programa GRC1", data: "2025-09-01", evidencia: "arquivo", emissor: "ABC da Construção", titulo: "The Inside Man: Temporada 3 Ep 05 – A Verdade Vos Libertará", arquivo: "cursos/abc-grc1-34-the-inside-man-t3-ep05-a-verdade-vos-libertara.pdf", programa: "Programa GRC1", duracao: "8 min", horas: 0.133 },
  { id: "abc-grc1-35-the-inside-man-t3-ep11-a-chumbada", secao: "ABC — Programa GRC1", data: "2026-02-04", evidencia: "arquivo", emissor: "ABC da Construção", titulo: "The Inside Man: Temporada 3 Ep 11 – A Chumbada", arquivo: "cursos/abc-grc1-35-the-inside-man-t3-ep11-a-chumbada.pdf", programa: "Programa GRC1", duracao: "7 min", horas: 0.117 },
  { id: "alura-one-20230526-formacao-desenvolvimento-pessoal-t5", secao: "Alura — Programa ONE", data: "2023-05-26", evidencia: "arquivo", emissor: "Alura", titulo: "Desenvolvimento Pessoal T5", arquivo: "cursos/alura-one-20230526-formacao-desenvolvimento-pessoal-t5.pdf", programa: "Programa ONE", tipo: "Formação", duracao: "38 h", horas: 38, papel: "Concluinte" },
  { id: "alura-one-20230529-formacao-iniciante-em-programacao-t5", secao: "Alura — Programa ONE", data: "2023-05-29", evidencia: "arquivo", emissor: "Alura", titulo: "Iniciante em programacao t5", arquivo: "cursos/alura-one-20230529-formacao-iniciante-em-programacao-t5.pdf", programa: "Programa ONE", tipo: "Formação", duracao: "71 h", horas: 71, papel: "Concluinte" },
  { id: "alura-one-20230530-declaracao-cursos-e-formacoes", secao: "Alura — Programa ONE", data: "2023-05-30", evidencia: "arquivo", emissor: "Alura", titulo: "Declaração de cursos e formações", arquivo: "cursos/alura-one-20230530-declaracao-cursos-e-formacoes.pdf", programa: "Programa ONE", tipo: "Declaração", papel: "Concluinte", emissao: "2023-04-18" },
  { id: "alura-one-20231003-curso-business-model-canvas-parte-2", secao: "Alura — Programa ONE", data: "2023-10-03", evidencia: "arquivo", emissor: "Alura", titulo: "Business model canvas parte 2", arquivo: "cursos/alura-one-20231003-curso-business-model-canvas-parte-2.pdf", programa: "Programa ONE", tipo: "Curso", duracao: "8 h", horas: 8, papel: "Concluinte" },
  { id: "dio-santander-20220606-conheca-as-oportunidades-da-dio", secao: "DIO — Bootcamp Santander", data: "2022-06-06", evidencia: "arquivo", emissor: "DIO", titulo: "Conheça as Oportunidades da DIO", arquivo: "cursos/dio-santander-20220606-conheca-as-oportunidades-da-dio.pdf", programa: "Bootcamp Santander", duracao: "1 h", horas: 1, papel: "Concluinte", codigo: "BCA575E8" },
  { id: "dio-santander-20220606-seja-protagonista-neste-bootcamp", secao: "DIO — Bootcamp Santander", data: "2022-06-06", evidencia: "arquivo", emissor: "DIO", titulo: "Seja Protagonista Neste Bootcamp", arquivo: "cursos/dio-santander-20220606-seja-protagonista-neste-bootcamp.pdf", programa: "Bootcamp Santander", duracao: "1 h", horas: 1, papel: "Concluinte", codigo: "434BB33A" },
  { id: "dio-santander-20220623-introducao-pratica-ao-typescript", secao: "DIO — Bootcamp Santander", data: "2022-06-23", evidencia: "arquivo", emissor: "DIO", titulo: "Introdução Prática ao TypeScript", arquivo: "cursos/dio-santander-20220623-introducao-pratica-ao-typescript.pdf", programa: "Bootcamp Santander", duracao: "2 h", horas: 2, papel: "Concluinte", codigo: "F5827D34" },
  { id: "dio-spread-fullstack-00-boas-vindas-ao-bootcamp", secao: "DIO — Bootcamp Spread Fullstack", data: "2022-04-18", evidencia: "arquivo", emissor: "DIO", titulo: "Boas-vindas ao Bootcamp: Spread Fullstack Developer", arquivo: "cursos/dio-spread-fullstack-00-boas-vindas-ao-bootcamp.pdf", programa: "Bootcamp Spread Fullstack", duracao: "1 h", horas: 1, papel: "Concluinte", codigo: "76A52EE8" },
  { id: "dio-spread-fullstack-01-logica-de-programacao-essencial", secao: "DIO — Bootcamp Spread Fullstack", data: "2022-04-18", evidencia: "arquivo", emissor: "DIO", titulo: "Lógica de Programação Essencial", arquivo: "cursos/dio-spread-fullstack-01-logica-de-programacao-essencial.pdf", programa: "Bootcamp Spread Fullstack", duracao: "4 h", horas: 4, papel: "Concluinte", codigo: "639C4791" },
  { id: "dio-spread-fullstack-02-introducao-ao-git-e-ao-github", secao: "DIO — Bootcamp Spread Fullstack", data: "2022-04-19", evidencia: "arquivo", emissor: "DIO", titulo: "Introdução ao Git e ao GitHub", arquivo: "cursos/dio-spread-fullstack-02-introducao-ao-git-e-ao-github.pdf", programa: "Bootcamp Spread Fullstack", duracao: "5 h", horas: 5, papel: "Concluinte", codigo: "81A44A25" },
  { id: "dio-spread-fullstack-03-criando-seu-primeiro-repositorio-no-github", secao: "DIO — Bootcamp Spread Fullstack", data: "2022-04-19", evidencia: "arquivo", emissor: "DIO", titulo: "Criando seu Primeiro Repositório no GitHub Para Compartilhar Seu Progresso", arquivo: "cursos/dio-spread-fullstack-03-criando-seu-primeiro-repositorio-no-github.pdf", programa: "Bootcamp Spread Fullstack", duracao: "1 h", horas: 1, papel: "Concluinte", codigo: "E3094523" },
  { id: "dio-spread-fullstack-04-primeiros-passos-para-desenvolvimento-web", secao: "DIO — Bootcamp Spread Fullstack", data: "2022-04-26", evidencia: "arquivo", emissor: "DIO", titulo: "Primeiros passos para desenvolvimento web", arquivo: "cursos/dio-spread-fullstack-04-primeiros-passos-para-desenvolvimento-web.pdf", programa: "Bootcamp Spread Fullstack", duracao: "6 h", horas: 6, papel: "Concluinte", codigo: "9093CE8A" },
  { id: "dio-spread-fullstack-05-introducao-a-criacao-de-websites-com-html5-e-css3", secao: "DIO — Bootcamp Spread Fullstack", data: "2022-04-27", evidencia: "arquivo", emissor: "DIO", titulo: "Introdução a criação de websites com HTML5 e CSS3", arquivo: "cursos/dio-spread-fullstack-05-introducao-a-criacao-de-websites-com-html5-e-css3.pdf", programa: "Bootcamp Spread Fullstack", duracao: "6 h", horas: 6, papel: "Concluinte", codigo: "A7D26BEE" },
  { id: "dio-spread-fullstack-06-posicionando-elementos-com-flexbox-em-css", secao: "DIO — Bootcamp Spread Fullstack", data: "2022-05-20", evidencia: "arquivo", emissor: "DIO", titulo: "Posicionando elementos com Flexbox em CSS", arquivo: "cursos/dio-spread-fullstack-06-posicionando-elementos-com-flexbox-em-css.pdf", programa: "Bootcamp Spread Fullstack", duracao: "4 h", horas: 4, papel: "Concluinte", codigo: "49D0FE18" },
  { id: "dio-spread-fullstack-07-recriando-a-pagina-inicial-do-instagram", secao: "DIO — Bootcamp Spread Fullstack", data: "2022-05-24", evidencia: "arquivo", emissor: "DIO", titulo: "Recriando a página inicial do Instagram", arquivo: "cursos/dio-spread-fullstack-07-recriando-a-pagina-inicial-do-instagram.pdf", programa: "Bootcamp Spread Fullstack", duracao: "2 h", horas: 2, papel: "Concluinte", codigo: "E432630F" },
  { id: "dio-spread-fullstack-08-introducao-ao-javascript", secao: "DIO — Bootcamp Spread Fullstack", data: "2022-05-25", evidencia: "arquivo", emissor: "DIO", titulo: "Introdução ao JavaScript", arquivo: "cursos/dio-spread-fullstack-08-introducao-ao-javascript.pdf", programa: "Bootcamp Spread Fullstack", duracao: "3 h", horas: 3, papel: "Concluinte", codigo: "EBE90FE9" },
  { id: "dio-spread-fullstack-09-sintaxe-e-operadores", secao: "DIO — Bootcamp Spread Fullstack", data: "2022-05-27", evidencia: "arquivo", emissor: "DIO", titulo: "Sintaxe e Operadores", arquivo: "cursos/dio-spread-fullstack-09-sintaxe-e-operadores.pdf", programa: "Bootcamp Spread Fullstack", duracao: "2 h", horas: 2, papel: "Concluinte", codigo: "9F691C73" },
  { id: "dio-spread-fullstack-10-variaveis-e-tipos", secao: "DIO — Bootcamp Spread Fullstack", data: "2022-06-09", evidencia: "arquivo", emissor: "DIO", titulo: "Variáveis e Tipos", arquivo: "cursos/dio-spread-fullstack-10-variaveis-e-tipos.pdf", programa: "Bootcamp Spread Fullstack", duracao: "3 h", horas: 3, papel: "Concluinte", codigo: "1C08F528" },
  { id: "dio-spread-fullstack-11-funcoes", secao: "DIO — Bootcamp Spread Fullstack", data: "2022-06-09", evidencia: "arquivo", emissor: "DIO", titulo: "Funções", arquivo: "cursos/dio-spread-fullstack-11-funcoes.pdf", programa: "Bootcamp Spread Fullstack", duracao: "1 h", horas: 1, papel: "Concluinte", codigo: "7D81D3B6" },
  { id: "dio-spread-fullstack-12-colecoes", secao: "DIO — Bootcamp Spread Fullstack", data: "2022-06-10", evidencia: "arquivo", emissor: "DIO", titulo: "Coleções", arquivo: "cursos/dio-spread-fullstack-12-colecoes.pdf", programa: "Bootcamp Spread Fullstack", duracao: "1 h", horas: 1, papel: "Concluinte", codigo: "AA68BDAB" },
  { id: "dio-spread-fullstack-13-map-filter-e-reduce", secao: "DIO — Bootcamp Spread Fullstack", data: "2022-06-14", evidencia: "arquivo", emissor: "DIO", titulo: "Map, Filter e Reduce", arquivo: "cursos/dio-spread-fullstack-13-map-filter-e-reduce.pdf", programa: "Bootcamp Spread Fullstack", duracao: "2 h", horas: 2, papel: "Concluinte", codigo: "765B4DAD" },
  { id: "dio-spread-fullstack-14-debugging-e-error-handling", secao: "DIO — Bootcamp Spread Fullstack", data: "2022-06-14", evidencia: "arquivo", emissor: "DIO", titulo: "Debugging e Error Handling", arquivo: "cursos/dio-spread-fullstack-14-debugging-e-error-handling.pdf", programa: "Bootcamp Spread Fullstack", duracao: "2 h", horas: 2, papel: "Concluinte", codigo: "571F73B5" },
  { id: "dio-spread-fullstack-15-javascript-assincrono", secao: "DIO — Bootcamp Spread Fullstack", data: "2022-06-14", evidencia: "arquivo", emissor: "DIO", titulo: "Javascript Assíncrono", arquivo: "cursos/dio-spread-fullstack-15-javascript-assincrono.pdf", programa: "Bootcamp Spread Fullstack", duracao: "1 h", horas: 1, papel: "Concluinte", codigo: "B573CC16" },
  { id: "dio-spread-fullstack-16-orientacao-a-objetos", secao: "DIO — Bootcamp Spread Fullstack", data: "2022-06-14", evidencia: "arquivo", emissor: "DIO", titulo: "Orientação a objetos", arquivo: "cursos/dio-spread-fullstack-16-orientacao-a-objetos.pdf", programa: "Bootcamp Spread Fullstack", duracao: "1 h", horas: 1, papel: "Concluinte", codigo: "3C98FCBA" },
  { id: "dio-spread-fullstack-17-trabalhando-com-modulos-em-javascript", secao: "DIO — Bootcamp Spread Fullstack", data: "2022-06-14", evidencia: "arquivo", emissor: "DIO", titulo: "Trabalhando com Módulos em JavaScript", arquivo: "cursos/dio-spread-fullstack-17-trabalhando-com-modulos-em-javascript.pdf", programa: "Bootcamp Spread Fullstack", duracao: "1 h", horas: 1, papel: "Concluinte", codigo: "DDD4228E" },
  { id: "dio-spread-fullstack-18-manipulando-a-dom-com-javascript", secao: "DIO — Bootcamp Spread Fullstack", data: "2022-06-14", evidencia: "arquivo", emissor: "DIO", titulo: "Manipulando a D.O.M. com JavaScript", arquivo: "cursos/dio-spread-fullstack-18-manipulando-a-dom-com-javascript.pdf", programa: "Bootcamp Spread Fullstack", duracao: "1 h", horas: 1, papel: "Concluinte", codigo: "FBF057EB" },
  { id: "dio-spread-fullstack-19-introducao-ao-typescript-classes-tipos-e-interfaces", secao: "DIO — Bootcamp Spread Fullstack", data: "2022-06-20", evidencia: "arquivo", emissor: "DIO", titulo: "Introdução ao TypeScript: Explorando Classes, Tipos e Interfaces", arquivo: "cursos/dio-spread-fullstack-19-introducao-ao-typescript-classes-tipos-e-interfaces.pdf", programa: "Bootcamp Spread Fullstack", duracao: "2 h", horas: 2, papel: "Concluinte", codigo: "8D6EA45E" },
  { id: "dio-spread-fullstack-20-sistema-de-estacionamento-com-typescript", secao: "DIO — Bootcamp Spread Fullstack", data: "2022-06-22", evidencia: "arquivo", emissor: "DIO", titulo: "Aprenda a criar um sistema de estacionamento usando TypeScript", arquivo: "cursos/dio-spread-fullstack-20-sistema-de-estacionamento-com-typescript.pdf", programa: "Bootcamp Spread Fullstack", duracao: "2 h", horas: 2, papel: "Concluinte", codigo: "3F348E21" },
  { id: "dio-spread-fullstack-21-introducao-ao-reactjs", secao: "DIO — Bootcamp Spread Fullstack", data: "2022-07-15", evidencia: "arquivo", emissor: "DIO", titulo: "Introdução ao ReactJS", arquivo: "cursos/dio-spread-fullstack-21-introducao-ao-reactjs.pdf", programa: "Bootcamp Spread Fullstack", duracao: "3 h", horas: 3, papel: "Concluinte", codigo: "71963BF9" },
  { id: "dio-spread-fullstack-22-introducao-aos-react-hooks", secao: "DIO — Bootcamp Spread Fullstack", data: "2022-07-16", evidencia: "arquivo", emissor: "DIO", titulo: "Introdução aos React Hooks", arquivo: "cursos/dio-spread-fullstack-22-introducao-aos-react-hooks.pdf", programa: "Bootcamp Spread Fullstack", duracao: "5 h", horas: 5, papel: "Concluinte", codigo: "C3D2E365" },
  { id: "dio-spread-fullstack-23-states-e-effects-no-reactjs", secao: "DIO — Bootcamp Spread Fullstack", data: "2022-07-16", evidencia: "arquivo", emissor: "DIO", titulo: "Trabalhando com States & Effects no ReactJs", arquivo: "cursos/dio-spread-fullstack-23-states-e-effects-no-reactjs.pdf", programa: "Bootcamp Spread Fullstack", duracao: "2 h", horas: 2, papel: "Concluinte", codigo: "C10106D1" },
  { id: "dio-spread-fullstack-24-desenvolvimento-de-aplicacoes-para-internet-com-reactjs", secao: "DIO — Bootcamp Spread Fullstack", data: "2022-07-19", evidencia: "arquivo", emissor: "DIO", titulo: "Desenvolvimento de aplicações para internet com ReactJS", arquivo: "cursos/dio-spread-fullstack-24-desenvolvimento-de-aplicacoes-para-internet-com-reactjs.pdf", programa: "Bootcamp Spread Fullstack", duracao: "4 h", horas: 4, papel: "Concluinte", codigo: "EA83EBFE" },
  { id: "dio-spread-fullstack-25-praticas-avancadas-em-projetos-com-reactjs", secao: "DIO — Bootcamp Spread Fullstack", data: "2022-07-20", evidencia: "arquivo", emissor: "DIO", titulo: "Práticas avançadas em projetos com ReactJS", arquivo: "cursos/dio-spread-fullstack-25-praticas-avancadas-em-projetos-com-reactjs.pdf", programa: "Bootcamp Spread Fullstack", duracao: "4 h", horas: 4, papel: "Concluinte", codigo: "EC5BFB8F" },
  { id: "estacio-20230228-curso-prepara-tech", secao: "Cursos", data: "2023-02-28", evidencia: "arquivo", emissor: "Estácio", titulo: "PREPARA.TECH", arquivo: "cursos/estacio-20230228-curso-prepara-tech.pdf", tipo: "Curso", duracao: "15 h", horas: 15, papel: "Concluinte" },
  { id: "estacio-jf-20100128-curso-administracao-para-pequenas-empresas", secao: "Cursos", data: "2010-01-25", evidencia: "arquivo", emissor: "Estácio de Sá — Juiz de Fora", titulo: "Administração Inteligente para Pequenas Empresas", arquivo: "cursos/estacio-jf-20100128-curso-administracao-para-pequenas-empresas.jpeg", tipo: "Curso", duracao: "16 h", horas: 16, papel: "Participante", emissao: "2010-01-28" },
  { id: "rocketseat-discover-20220607-trilha-1-conectar", secao: "Rocketseat Discover", data: "2022-06-07", evidencia: "arquivo", emissor: "Rocketseat", titulo: "Trilha Conectar", arquivo: "cursos/rocketseat-discover-20220607-trilha-1-conectar.pdf", programa: "Discover", tipo: "Trilha", duracao: "2.38 h", horas: 2.38, papel: "Concluinte" },
  { id: "rocketseat-discover-20220607-trilha-2-fundamentar", secao: "Rocketseat Discover", data: "2022-06-07", evidencia: "arquivo", emissor: "Rocketseat", titulo: "Trilha Fundamentar", arquivo: "cursos/rocketseat-discover-20220607-trilha-2-fundamentar.pdf", programa: "Discover", tipo: "Trilha", duracao: "29.22 h", horas: 29.22, papel: "Concluinte" },
  { id: "rocketseat-discover-20220913-trilha-3-especializar", secao: "Rocketseat Discover", data: "2022-09-13", evidencia: "arquivo", emissor: "Rocketseat", titulo: "Trilha Especializar", arquivo: "cursos/rocketseat-discover-20220913-trilha-3-especializar.pdf", programa: "Discover", tipo: "Trilha", duracao: "11.18 h", horas: 11.18, papel: "Concluinte" },
  { id: "startse-20220700-tech-academy", secao: "Cursos", data: "2022-07", evidencia: "arquivo", emissor: "StartSe", titulo: "Tech Academy", arquivo: "cursos/startse-20220700-tech-academy.pdf", duracao: "100 h", horas: 100, papel: "Concluinte" },
  { id: "startse-20220900-soft-skills-jornada-para-o-futuro", secao: "Cursos", data: "2022-09", evidencia: "arquivo", emissor: "StartSe", titulo: "Soft Skills — Jornada para o Futuro", arquivo: "cursos/startse-20220900-soft-skills-jornada-para-o-futuro.pdf", duracao: "10 h", horas: 10, papel: "Concluinte" },
  { id: "udesc-20120913-curso-logica-de-programacao-100h", secao: "Cursos", data: "2012-09-13", evidencia: "arquivo", emissor: "UDESC", titulo: "Curso de Lógica de Programação", arquivo: "cursos/udesc-20120913-curso-logica-de-programacao-100h.pdf", tipo: "Curso", duracao: "100 h", horas: 100, papel: "Participante", emissao: "2012-08-06" },
  { id: "ufjf-20110603-minicurso-programacao", secao: "Cursos", data: "2011-06-03", evidencia: "arquivo", emissor: "UFJF", titulo: "Programação", arquivo: "cursos/ufjf-20110603-minicurso-programacao.pdf", tipo: "Minicurso", duracao: "2 h", horas: 2, papel: "Participante", evento: "I Getmeeting", emissao: "2011-06-04" },
  { id: "ufjf-20111017-minicurso-analise-de-redes-sociais", secao: "Cursos", data: "2011-10-17", evidencia: "arquivo", emissor: "UFJF", titulo: "Análise De Redes Sociais", arquivo: "cursos/ufjf-20111017-minicurso-analise-de-redes-sociais.pdf", tipo: "Minicurso", duracao: "4 h", horas: 4, papel: "Participante", evento: "Xv Semana De Computação" },
  { id: "ufjf-20111017-minicurso-desenvolvimento-de-jogos-com-unity3d", secao: "Cursos", data: "2011-10-17", evidencia: "arquivo", emissor: "UFJF", titulo: "Desenvolvimento De Jogos Com Unity3D", arquivo: "cursos/ufjf-20111017-minicurso-desenvolvimento-de-jogos-com-unity3d.pdf", tipo: "Minicurso", duracao: "4 h", horas: 4, papel: "Participante", evento: "Xv Semana De Computação" },
  { id: "ufjf-20120328-minicurso-criando-websites-com-o-wordpress", secao: "Cursos", data: "2012-03-28", evidencia: "arquivo", emissor: "UFJF", titulo: "Criando Websites Com O Wordpress", arquivo: "cursos/ufjf-20120328-minicurso-criando-websites-com-o-wordpress.pdf", tipo: "Minicurso", duracao: "4 h", horas: 4, papel: "Participante", evento: "Vi Getupdate" },
  { id: "ufjf-20121123-minicursos-eri-mg-html5-e-mineracao-de-dados", secao: "Cursos", data: "2012-11-23", evidencia: "arquivo", emissor: "UFJF", titulo: "ERI MG HTML5 e mineracao de dados", arquivo: "cursos/ufjf-20121123-minicursos-eri-mg-html5-e-mineracao-de-dados.pdf", tipo: "Minicurso", duracao: "3 h", horas: 3, papel: "Participante", emissao: "2012-11-24" },
  { id: "ufjf-20130524-minicurso-php-e-mysql-para-iniciantes", secao: "Cursos", data: "2013-05-24", evidencia: "arquivo", emissor: "UFJF", titulo: "Php E Mysql Para Iniciantes", arquivo: "cursos/ufjf-20130524-minicurso-php-e-mysql-para-iniciantes.pdf", tipo: "Minicurso", duracao: "3 h", horas: 3, papel: "Participante", evento: "Iii Getmeeting", emissao: "2013-05-25" },
  { id: "ufjf-20130524-minicurso-sistemas-de-controle-de-versao", secao: "Cursos", data: "2013-05-24", evidencia: "arquivo", emissor: "UFJF", titulo: "Realizando Projetos De Forma Segura Utilizando Sistemas De Controle De Versão", arquivo: "cursos/ufjf-20130524-minicurso-sistemas-de-controle-de-versao.pdf", tipo: "Minicurso", duracao: "3 h", horas: 3, papel: "Participante", evento: "Iii Getmeeting", emissao: "2013-05-25" },
  { id: "voitto-20231030-fundamentos-de-powerpoint", secao: "Cursos", data: "2023-10-30", evidencia: "arquivo", emissor: "Grupo Voitto", titulo: "Fundamentos de PowerPoint", arquivo: "cursos/voitto-20231030-fundamentos-de-powerpoint.pdf", duracao: "3 h", horas: 3, papel: "Concluinte", codigo: "5143551301" },
  { id: "voitto-20231031-produtividade-e-gestao-de-tempo", secao: "Cursos", data: "2023-10-31", evidencia: "arquivo", emissor: "Grupo Voitto", titulo: "Produtividade e Gestão de Tempo", arquivo: "cursos/voitto-20231031-produtividade-e-gestao-de-tempo.pdf", duracao: "8 h", horas: 8, papel: "Concluinte", codigo: "2123551301" },
  { id: "voitto-20231101-fundamentos-de-lideranca", secao: "Cursos", data: "2023-11-01", evidencia: "arquivo", emissor: "Grupo Voitto", titulo: "Fundamentos de Liderança", arquivo: "cursos/voitto-20231101-fundamentos-de-lideranca.pdf", duracao: "8 h", horas: 8, papel: "Organizador", codigo: "5093551301" },
  { id: "voitto-20240125-aprendizado-agil", secao: "Cursos", data: "2024-01-25", evidencia: "arquivo", emissor: "Grupo Voitto", titulo: "Aprendizado Ágil", arquivo: "cursos/voitto-20240125-aprendizado-agil.pdf", duracao: "7 h", horas: 7, papel: "Organizador", codigo: "5250551301" },
  { id: "voitto-20240305-excel-avancado", secao: "Cursos", data: "2024-03-05", evidencia: "arquivo", emissor: "Grupo Voitto", titulo: "Excel Avançado", arquivo: "cursos/voitto-20240305-excel-avancado.pdf", duracao: "24 h", horas: 24, papel: "Concluinte", codigo: "3470551301" },
  { id: "voitto-20240325-discord-para-empresas", secao: "Cursos", data: "2024-03-25", evidencia: "arquivo", emissor: "Grupo Voitto", titulo: "Discord para empresas", arquivo: "cursos/voitto-20240325-discord-para-empresas.pdf", duracao: "4 h", horas: 4, papel: "Concluinte", codigo: "5177551301" },
  { id: "voitto-20240325-home-office-de-alta-performance", secao: "Cursos", data: "2024-03-25", evidencia: "arquivo", emissor: "Grupo Voitto", titulo: "Home Office de Alta Performance", arquivo: "cursos/voitto-20240325-home-office-de-alta-performance.pdf", duracao: "8 h", horas: 8, papel: "Concluinte", codigo: "4496551301" },
  { id: "voitto-20240325-slack-para-ambientes-corporativos", secao: "Cursos", data: "2024-03-25", evidencia: "arquivo", emissor: "Grupo Voitto", titulo: "Slack para Ambientes Corporativos", arquivo: "cursos/voitto-20240325-slack-para-ambientes-corporativos.pdf", duracao: "2 h", horas: 2, papel: "Concluinte", codigo: "5183551301" },
  { id: "voitto-20240325-trello-para-gestao-de-negocios", secao: "Cursos", data: "2024-03-25", evidencia: "arquivo", emissor: "Grupo Voitto", titulo: "Trello para Gestão de Negócios", arquivo: "cursos/voitto-20240325-trello-para-gestao-de-negocios.pdf", duracao: "4 h", horas: 4, papel: "Organizador", codigo: "5146551301" },
  { id: "voitto-20240326-como-ter-sucesso-em-um-processo-seletivo", secao: "Cursos", data: "2024-03-26", evidencia: "arquivo", emissor: "Grupo Voitto", titulo: "Como ter sucesso em um Processo Seletivo", arquivo: "cursos/voitto-20240326-como-ter-sucesso-em-um-processo-seletivo.pdf", duracao: "5 h", horas: 5, papel: "Concluinte", codigo: "5180551301" },
  { id: "voitto-20240326-crm-gestao-de-relacionamento-com-o-cliente", secao: "Cursos", data: "2024-03-26", evidencia: "arquivo", emissor: "Grupo Voitto", titulo: "CRM: Gestão de Relacionamento com o Cliente", arquivo: "cursos/voitto-20240326-crm-gestao-de-relacionamento-com-o-cliente.pdf", duracao: "4 h", horas: 4, papel: "Concluinte", codigo: "5274551301" },
  { id: "voitto-20240326-fundamentos-de-consultoria", secao: "Cursos", data: "2024-03-26", evidencia: "arquivo", emissor: "Grupo Voitto", titulo: "Fundamentos de Consultoria", arquivo: "cursos/voitto-20240326-fundamentos-de-consultoria.pdf", duracao: "12 h", horas: 12, papel: "Concluinte", codigo: "3232551301" },
  { id: "voitto-20240326-oratoria-de-alta-performance", secao: "Cursos", data: "2024-03-26", evidencia: "arquivo", emissor: "Grupo Voitto", titulo: "Oratória de Alta Performance", arquivo: "cursos/voitto-20240326-oratoria-de-alta-performance.pdf", duracao: "16 h", horas: 16, papel: "Organizador", codigo: "4477551301" },
  { id: "voitto-20240327-branding-como-ser-a-unica-opcao-na-mente-do-seu-cliente", secao: "Cursos", data: "2024-03-27", evidencia: "arquivo", emissor: "Grupo Voitto", titulo: "Branding: Como ser a única opção na mente do seu cliente", arquivo: "cursos/voitto-20240327-branding-como-ser-a-unica-opcao-na-mente-do-seu-cliente.pdf", duracao: "8 h", horas: 8, papel: "Concluinte", codigo: "5194551301" },
  { id: "voitto-20240327-financas-pessoais", secao: "Cursos", data: "2024-03-27", evidencia: "arquivo", emissor: "Grupo Voitto", titulo: "Finanças Pessoais", arquivo: "cursos/voitto-20240327-financas-pessoais.pdf", duracao: "14 h", horas: 14, papel: "Organizador", codigo: "4369551301" },
  { id: "voitto-20240328-fundamentos-de-user-experience", secao: "Cursos", data: "2024-03-28", evidencia: "arquivo", emissor: "Grupo Voitto", titulo: "Fundamentos de User Experience", arquivo: "cursos/voitto-20240328-fundamentos-de-user-experience.pdf", duracao: "4 h", horas: 4, papel: "Concluinte", codigo: "5084551301" },
  { id: "voitto-20240328-fundamentos-do-growth-hacking", secao: "Cursos", data: "2024-03-28", evidencia: "arquivo", emissor: "Grupo Voitto", titulo: "Fundamentos do Growth Hacking", arquivo: "cursos/voitto-20240328-fundamentos-do-growth-hacking.pdf", duracao: "3 h", horas: 3, papel: "Organizador", codigo: "4246551301" },
  { id: "voitto-20240401-fundamentos-de-demissao", secao: "Cursos", data: "2024-04-01", evidencia: "arquivo", emissor: "Grupo Voitto", titulo: "Fundamentos de Demissão", arquivo: "cursos/voitto-20240401-fundamentos-de-demissao.pdf", duracao: "2 h", horas: 2, papel: "Concluinte", codigo: "5169551301" },
  { id: "voitto-20240401-workshop-ingles-para-processos-seletivos", secao: "Cursos", data: "2024-04-01", evidencia: "arquivo", emissor: "Grupo Voitto", titulo: "Workshop Inglês para Processos Seletivos", arquivo: "cursos/voitto-20240401-workshop-ingles-para-processos-seletivos.pdf", tipo: "Workshop", duracao: "3 h", horas: 3, papel: "Concluinte", codigo: "4193551301" },
  { id: "voitto-20240402-fundamentos-de-gerenciamento-de-projetos", secao: "Cursos", data: "2024-04-02", evidencia: "arquivo", emissor: "Grupo Voitto", titulo: "Fundamentos de Gerenciamento de Projetos", arquivo: "cursos/voitto-20240402-fundamentos-de-gerenciamento-de-projetos.pdf", duracao: "8 h", horas: 8, papel: "Organizador", codigo: "4167551301" },
  { id: "voitto-20240402-lean-office-na-pratica", secao: "Cursos", data: "2024-04-02", evidencia: "arquivo", emissor: "Grupo Voitto", titulo: "Lean Office na Prática", arquivo: "cursos/voitto-20240402-lean-office-na-pratica.pdf", duracao: "8 h", horas: 8, papel: "Concluinte", codigo: "5115551301" },
  { id: "voitto-20240404-fundamentos-de-power-bi", secao: "Cursos", data: "2024-04-04", evidencia: "arquivo", emissor: "Grupo Voitto", titulo: "Fundamentos de Power BI", arquivo: "cursos/voitto-20240404-fundamentos-de-power-bi.pdf", duracao: "6 h", horas: 6, papel: "Concluinte", codigo: "5383551301" },
  { id: "voitto-20240404-fundamentos-do-customer-success", secao: "Cursos", data: "2024-04-04", evidencia: "arquivo", emissor: "Grupo Voitto", titulo: "Fundamentos do Customer Success", arquivo: "cursos/voitto-20240404-fundamentos-do-customer-success.pdf", duracao: "8 h", horas: 8, papel: "Concluinte", codigo: "5172551301" },
  { id: "voitto-20240404-workshop-marketing-digital", secao: "Cursos", data: "2024-04-04", evidencia: "arquivo", emissor: "Grupo Voitto", titulo: "Workshop Marketing Digital", arquivo: "cursos/voitto-20240404-workshop-marketing-digital.pdf", tipo: "Workshop", duracao: "3 h", horas: 3, papel: "Concluinte", codigo: "4102551301" },
  { id: "voitto-20240405-criatividade-e-resolucao-de-problemas", secao: "Cursos", data: "2024-04-05", evidencia: "arquivo", emissor: "Grupo Voitto", titulo: "Criatividade e Resolução de Problemas", arquivo: "cursos/voitto-20240405-criatividade-e-resolucao-de-problemas.pdf", duracao: "9 h", horas: 9, papel: "Concluinte", codigo: "5066551301" },
  { id: "voitto-20240405-pensamento-critico-e-analitico", secao: "Cursos", data: "2024-04-05", evidencia: "arquivo", emissor: "Grupo Voitto", titulo: "Pensamento Crítico e Analítico", arquivo: "cursos/voitto-20240405-pensamento-critico-e-analitico.pdf", duracao: "8 h", horas: 8, papel: "Concluinte", codigo: "4808551301" },
  { id: "voitto-20240408-comunicacao-interpessoal-e-feedback", secao: "Cursos", data: "2024-04-08", evidencia: "arquivo", emissor: "Grupo Voitto", titulo: "Comunicação Interpessoal e Feedback", arquivo: "cursos/voitto-20240408-comunicacao-interpessoal-e-feedback.pdf", duracao: "16 h", horas: 16, papel: "Organizador", codigo: "1479551301" },
  { id: "voitto-20240408-estruturacao-de-okrs", secao: "Cursos", data: "2024-04-08", evidencia: "arquivo", emissor: "Grupo Voitto", titulo: "Estruturação de OKR's", arquivo: "cursos/voitto-20240408-estruturacao-de-okrs.pdf", duracao: "5 h", horas: 5, papel: "Organizador", codigo: "5064551301" },
  { id: "voitto-20240826-inteligencia-emocional", secao: "Cursos", data: "2024-08-26", evidencia: "arquivo", emissor: "Grupo Voitto", titulo: "Inteligência Emocional", arquivo: "cursos/voitto-20240826-inteligencia-emocional.pdf", duracao: "16 h", horas: 16, papel: "Organizador", codigo: "4610551301" },
  { id: "voitto-20240826-workshop-personal-branding", secao: "Cursos", data: "2024-08-26", evidencia: "arquivo", emissor: "Grupo Voitto", titulo: "Workshop Personal Branding", arquivo: "cursos/voitto-20240826-workshop-personal-branding.pdf", tipo: "Workshop", duracao: "3 h", horas: 3, papel: "Concluinte", codigo: "4110551301" },
  { id: "voitto-20240827-gestao-de-conflitos", secao: "Cursos", data: "2024-08-27", evidencia: "arquivo", emissor: "Grupo Voitto", titulo: "Gestão de Conflitos", arquivo: "cursos/voitto-20240827-gestao-de-conflitos.pdf", duracao: "8 h", horas: 8, papel: "Organizador", codigo: "2126551301" },
  { id: "voitto-20240827-tecnicas-de-negociacao-e-persuasao", secao: "Cursos", data: "2024-08-27", evidencia: "arquivo", emissor: "Grupo Voitto", titulo: "Técnicas de Negociação e Persuasão", arquivo: "cursos/voitto-20240827-tecnicas-de-negociacao-e-persuasao.pdf", duracao: "8 h", horas: 8, papel: "Concluinte", codigo: "5120551301" },
  { id: "voitto-20240828-especialista-em-dashboard-de-gestao", secao: "Cursos", data: "2024-08-28", evidencia: "arquivo", emissor: "Grupo Voitto", titulo: "Especialista em Dashboard de Gestão", arquivo: "cursos/voitto-20240828-especialista-em-dashboard-de-gestao.pdf", duracao: "20 h", horas: 20, papel: "Concluinte", codigo: "2128551301" },
  { id: "voitto-20240829-fundamentos-de-copywriting", secao: "Cursos", data: "2024-08-29", evidencia: "arquivo", emissor: "Grupo Voitto", titulo: "Fundamentos de Copywriting", arquivo: "cursos/voitto-20240829-fundamentos-de-copywriting.pdf", duracao: "6 h", horas: 6, papel: "Concluinte", codigo: "5255551301" },
  { id: "voitto-20240829-fundamentos-de-storytelling", secao: "Cursos", data: "2024-08-29", evidencia: "arquivo", emissor: "Grupo Voitto", titulo: "Fundamentos de Storytelling", arquivo: "cursos/voitto-20240829-fundamentos-de-storytelling.pdf", duracao: "4 h", horas: 4, papel: "Concluinte", codigo: "5140551301" },
  { id: "voitto-20240829-power-bi-aplicado-a-negocios", secao: "Cursos", data: "2024-08-29", evidencia: "arquivo", emissor: "Grupo Voitto", titulo: "Power BI Aplicado a Negócios", arquivo: "cursos/voitto-20240829-power-bi-aplicado-a-negocios.pdf", duracao: "24 h", horas: 24, papel: "Concluinte", codigo: "4236551301" },
  { id: "voitto-20240830-propriedade-intelectual-e-direitos-de-marcas-e-patentes", secao: "Cursos", data: "2024-08-30", evidencia: "arquivo", emissor: "Grupo Voitto", titulo: "Propriedade Intelectual e Direitos de Marcas e Patentes", arquivo: "cursos/voitto-20240830-propriedade-intelectual-e-direitos-de-marcas-e-patentes.pdf", duracao: "6 h", horas: 6, papel: "Concluinte", codigo: "4611551301" },
  { id: "voitto-20240831-business-model-canvas", secao: "Cursos", data: "2024-08-31", evidencia: "arquivo", emissor: "Grupo Voitto", titulo: "Business Model Canvas", arquivo: "cursos/voitto-20240831-business-model-canvas.pdf", duracao: "4 h", horas: 4, papel: "Concluinte", codigo: "5141551301" },
  { id: "voitto-20240831-design-thinking", secao: "Cursos", data: "2024-08-31", evidencia: "arquivo", emissor: "Grupo Voitto", titulo: "Design Thinking", arquivo: "cursos/voitto-20240831-design-thinking.pdf", duracao: "12 h", horas: 12, papel: "Concluinte", codigo: "5168551301" },
  { id: "voitto-20240910-industria-4-0", secao: "Cursos", data: "2024-09-10", evidencia: "arquivo", emissor: "Grupo Voitto", titulo: "Indústria 4.0", arquivo: "cursos/voitto-20240910-industria-4-0.pdf", duracao: "11 h", horas: 11, papel: "Organizador", codigo: "4036551301" },
  { id: "xpeducacao-20220805-minicamp-dev-e-data", secao: "Cursos", data: "2022-07-21", evidencia: "arquivo", emissor: "Faculdade XP Educação", titulo: "Minicamp Dev & Data", arquivo: "cursos/xpeducacao-20220805-minicamp-dev-e-data.pdf", duracao: "32 h", horas: 32, papel: "Concluinte", evento: "Processo Seletivo do 2º semestre de 2022 da graduação", emissao: "2022-08-05" },
  { id: "resilia-conecta---3-anos-capacitando-talentos", secao: "Eventos", data: "2022-11-09", evidencia: "arquivo", emissor: "Resilia Educação", titulo: "Resilia Conecta - 3 anos capacitando talentos", arquivo: "eventos/Resilia Conecta - 3 anos capacitando talentos.pdf", papel: "Participante" },
  { id: "beelab-20200217-qa-week-2020", secao: "Eventos", data: "2020-02-17", evidencia: "arquivo", emissor: "BeeLab", titulo: "QA week 2020", arquivo: "eventos/beelab-20200217-qa-week-2020.pdf" },
  { id: "capivara-tech-20260627-product-camp-pocket-jf-3a-edicao", secao: "Eventos", data: "2026-06-27", evidencia: "arquivo", emissor: "Capivara Tech", titulo: "Product Camp Pocket JF 3° edição, com o tema: “O Empreendedorcomo primeiro produteiro da empresa” e com carga horária total de 3 horas, realizado", arquivo: "eventos/capivara-tech-20260627-product-camp-pocket-jf-3a-edicao.pdf", papel: "Palestrante", evento: "Product Camp Pocket JF 3° edição, com o tema: “O Empreendedorcomo primeiro produteiro da empresa” e com carga horária total de 3 horas" },
  { id: "codexperience-20231021-zona-da-mata", secao: "Eventos", data: "2023-10-21", evidencia: "arquivo", emissor: "Codexperience", titulo: "CodeXperience Zona da Mata", arquivo: "eventos/codexperience-20231021-zona-da-mata.pdf", papel: "Organizador", emissao: "2023-10-22" },
  { id: "conect-ai-20260528-capacitacao", secao: "Eventos", data: "2026-05-28", evidencia: "arquivo", emissor: "Conect AI", titulo: "Capacitacao", arquivo: "eventos/conect-ai-20260528-capacitacao.pdf", papel: "Participante" },
  { id: "estacio-orientacao-de-carreira", secao: "Eventos", data: "2024-08", evidencia: "arquivo", emissor: "Estácio Carreiras", titulo: "Programa de Orientação de Carreiras", arquivo: "eventos/estacio-orientacao-de-carreira.pdf", duracao: "3 h", horas: 3, papel: "Ouvinte" },
  { id: "fator-s-20230519-challenge", secao: "Eventos", data: "2023-05-19", evidencia: "arquivo", emissor: "Fator S", titulo: "Challenge", arquivo: "eventos/fator-s-20230519-challenge.pdf", duracao: "18 h", horas: 18, papel: "Participante" },
  { id: "ifsudestemg-20160919-evento-ii-tecnohub", secao: "Eventos", data: "2016-09-19", evidencia: "arquivo", emissor: "IF Sudeste MG", titulo: "II TecnoHUB", arquivo: "eventos/ifsudestemg-20160919-evento-ii-tecnohub.jpeg", tipo: "Evento", duracao: "10 h", horas: 10, papel: "Participante", emissao: "2016-10-07" },
  { id: "minas-summit-20240626", secao: "Eventos", data: "2024-06-26", evidencia: "arquivo", emissor: "Minas Summit", titulo: "MINAS SUMMIT 2024", arquivo: "eventos/minas-summit-20240626.pdf", duracao: "16 h", horas: 16, papel: "Participante" },
  { id: "minas-summit-20250605", secao: "Eventos", data: "2025-06-05", evidencia: "arquivo", emissor: "Minas Summit", titulo: "Minas Summit 2025 - Inovação que move o mundo!", arquivo: "eventos/minas-summit-20250605.pdf", papel: "Participante", emissao: "2025-06-06" },
  { id: "minas-summit-20260617", secao: "Eventos", data: "2026-06-17", evidencia: "arquivo", emissor: "Minas Summit", titulo: "Minas Summit 2026", arquivo: "eventos/minas-summit-20260617.pdf", papel: "Participante", emissao: "2026-06-18" },
  { id: "ufjf-20081020-evento-semana-da-computacao", secao: "Eventos", data: "2008-10-20", evidencia: "arquivo", emissor: "UFJF", titulo: "Semana da Computação", arquivo: "eventos/ufjf-20081020-evento-semana-da-computacao.jpeg", tipo: "Evento", duracao: "8 h", horas: 8, papel: "Participante", evento: "Instituto de Ciências Exatas", emissao: "2009-03-02" },
  { id: "ufjf-20110825-seminario-estagio-curricular", secao: "Eventos", data: "2011-08-25", evidencia: "arquivo", emissor: "UFJF", titulo: "Seminário Estágio Curricular — Escola Básica e Universidade", arquivo: "eventos/ufjf-20110825-seminario-estagio-curricular.jpeg", tipo: "Seminário", papel: "Participante", evento: "Coordenação de Estágios da Faculdade de Educação" },
  { id: "ufjf-20111017-palestra-computacao-utilitaria-e-colaborativa", secao: "Eventos", data: "2011-10-17", evidencia: "arquivo", emissor: "UFJF", titulo: "Computação Utilitária E Colaborativa: Recursos Ao Alcance De Todo", arquivo: "eventos/ufjf-20111017-palestra-computacao-utilitaria-e-colaborativa.pdf", tipo: "Palestra", papel: "Participante", evento: "Xv Semana De Computação" },
  { id: "ufjf-20111017-palestra-internet-das-coisas-e-redes-de-sensores-sem-fio", secao: "Eventos", data: "2011-10-17", evidencia: "arquivo", emissor: "UFJF", titulo: "Viabilizando -Internet Das Coisas- A Partir De Redes De Sensores Sem Fio", arquivo: "eventos/ufjf-20111017-palestra-internet-das-coisas-e-redes-de-sensores-sem-fio.pdf", tipo: "Palestra", papel: "Participante", evento: "Xv Semana De Computação" },
  { id: "ufjf-20111017-palestra-nanotecnologia-e-computacao", secao: "Eventos", data: "2011-10-17", evidencia: "arquivo", emissor: "UFJF", titulo: "Nanotecnologia E Computação: Uma Convergência Em Prol Do Desenvolvi-Mento", arquivo: "eventos/ufjf-20111017-palestra-nanotecnologia-e-computacao.pdf", tipo: "Palestra", duracao: "4 h", horas: 4, papel: "Participante", evento: "Xv Semana De Computação" },
  { id: "ufjf-20111017-palestra-uma-panoramica-da-realidade-virtual", secao: "Eventos", data: "2011-10-17", evidencia: "arquivo", emissor: "UFJF", titulo: "Uma Panorâmica Da Realidade Virtual E Suas Aplicações", arquivo: "eventos/ufjf-20111017-palestra-uma-panoramica-da-realidade-virtual.pdf", tipo: "Palestra", papel: "Participante", evento: "Xv Semana De Computação" },
  { id: "ufjf-20121015-palestra-desafios-na-seguranca-da-informacao", secao: "Eventos", data: "2012-10-15", evidencia: "arquivo", emissor: "UFJF", titulo: "Desafios Na Segurança Da Informação", arquivo: "eventos/ufjf-20121015-palestra-desafios-na-seguranca-da-informacao.pdf", tipo: "Palestra", duracao: "1 h", horas: 1, papel: "Participante", evento: "Semana Da Computação 2012" },
  { id: "ufjf-20121121-evento-smc-2012-simposio-mineiro-de-computacao", secao: "Eventos", data: "2012-11-21", evidencia: "arquivo", emissor: "UFJF", titulo: "SMC 2012 simposio mineiro de computacao", arquivo: "eventos/ufjf-20121121-evento-smc-2012-simposio-mineiro-de-computacao.pdf", tipo: "Evento", duracao: "20 h", horas: 20, papel: "Participante", emissao: "2012-11-24" },
  { id: "ufjf-20130524-mesa-redonda-empregado-ou-empregador-na-computacao", secao: "Eventos", data: "2013-05-24", evidencia: "arquivo", emissor: "UFJF", titulo: "Empregado Ou Empregador Na Computação, Qual É A Melhor Opção-", arquivo: "eventos/ufjf-20130524-mesa-redonda-empregado-ou-empregador-na-computacao.pdf", tipo: "Mesa-redonda", duracao: "2 h", horas: 2, papel: "Participante", evento: "Iii Getmeeting", emissao: "2013-05-25" },
  { id: "ufjf-20130524-workshop-trabalhos-de-graduacao-e-pos-graduacao-dcc", secao: "Eventos", data: "2013-05-24", evidencia: "arquivo", emissor: "UFJF", titulo: "Workshop De Trabalhos De Graduação E Pós-Graduação Do Dcc", arquivo: "eventos/ufjf-20130524-workshop-trabalhos-de-graduacao-e-pos-graduacao-dcc.pdf", tipo: "Workshop", duracao: "3 h", horas: 3, papel: "Participante", evento: "Iii Getmeeting", emissao: "2013-05-25" },
  { id: "ufjf-leis-20250702-conexoes-em-foco", secao: "Eventos", data: "2025-07-02", evidencia: "arquivo", emissor: "UFJF — LEIS", titulo: "Conexões em Foco: Tecnologia, Dados e Inovação", arquivo: "eventos/ufjf-leis-20250702-conexoes-em-foco.pdf", programa: "Liga de Empreendedorismo, Inovação e Startups", duracao: "4 h 30 min", horas: 4.5, papel: "Ouvinte", emissao: "2025-08-17" },
  { id: "ufjf-leis-20250702-roda-de-conversa-dados-e-inovacao-em-marketing", secao: "Eventos", data: "2025-07-02", evidencia: "arquivo", emissor: "UFJF — LEIS", titulo: "Dados e Inovação em Marketing", arquivo: "eventos/ufjf-leis-20250702-roda-de-conversa-dados-e-inovacao-em-marketing.pdf", programa: "Liga de Empreendedorismo, Inovação e Startups", tipo: "Roda de conversa", duracao: "1 h", horas: 1, papel: "Ouvinte", evento: "Conexões em Foco: Tecnologia, Dados e Inovação" },
];

// Fim do acervo.
